# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
   Genre.create(name: 'Action')
   Genre.create(name: 'Adventure')
   Genre.create(name: 'Animation')
   Genre.create(name: 'Biography')
   Genre.create(name: 'Comedy')
   Genre.create(name: 'Crime')
   Genre.create(name: 'Documentary')
   Genre.create(name: 'Drama')
   Genre.create(name: 'Family')
   Genre.create(name: 'Fantasy')
   Genre.create(name: 'Film-Noir')
   Genre.create(name: 'History')
   Genre.create(name: 'Horror')
   Genre.create(name: 'Music')
   Genre.create(name: 'Musical')
   Genre.create(name: 'Mystery')
   Genre.create(name: 'Romance')
   Genre.create(name: 'Sci-Fi')
   Genre.create(name: 'Short')
   Genre.create(name: 'Sport')
   Genre.create(name: 'Thriller')
   Genre.create(name: 'War')
   Genre.create(name: 'Western')

   Movie.create(title: 'The Last of The Mohicans', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/d/dd/Mohicansposter.jpg')
   Movie.create(title: 'In the Name of The Father', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/f/f3/In_the_name_of_the_father_ver1.jpg')
   Movie.create(title: 'My Left Foot', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/0/0a/My_Left_Foot.jpg')
   Movie.create(title: 'The Tree of Life', release_date: '2015-08-19', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/tr/thumb/1/18/The_Tree_of_Life_%28Afi%C5%9F%29.jpg/800px-The_Tree_of_Life_%28Afi%C5%9F%29.jpg')
   Movie.create(title: 'Interstellar', release_date: '1995-07-08', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/tr/b/bc/Interstellar_film_poster.jpg')
   Movie.create(title: '2001: A Space Oddsey', release_date: '2000-06-11', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/e/ef/2001_A_Space_Odyssey_Style_B.jpg')
   Movie.create(title: 'Black Mirror', release_date: '2011-05-30', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/2/24/BlackMirrorTitleCard.jpg')
   Movie.create(title: 'Sherlock', release_date: '1899-07-23', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'http://www.dvdsreleasedates.com/covers/sherlock-season-two-dvd-cover-26.jpg')
   Movie.create(title: 'A Bittersweet Life', release_date: '1942-11-11', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/a/a8/A_Bittersweet_Life_Soundtrack.jpg')
   Movie.create(title: 'A Seperation', release_date: '2013-01-14', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/0/00/A_Separation.jpg')
   Movie.create(title: 'The Good, The Bad and The Ugly', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg')
   Movie.create(title: 'The Matrix', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/The_Matrix_Poster.jpg/220px-The_Matrix_Poster.jpg')
   Movie.create(title: 'There Will Be Blood', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/d/da/There_Will_Be_Blood_Poster.jpg')
	Movie.create(title: 'The Good, The Bad and The Weird', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/7/7a/The_Good,_the_Bad,_the_Weird_film_poster.jpg')
	Movie.create(title: 'Kış Uykusu', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/en/0/0a/Winter_Sleep_(Poster).jpg')
	Movie.create(title: 'Bir Zamanlar Anadolu\'da', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/tr/4/4b/Bir_Zamanlar_Anadoluda_afi%C5%9F.jpg')
	Movie.create(title: 'Üç Maymun', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'https://upload.wikimedia.org/wikipedia/tr/e/e8/%C3%9C%C3%A7maymun.jpg')


   Comment.create(movie_id: 1, user_id: 1, body: "abi çoh iyi yeaaa")
   Comment.create(movie_id: 1, user_id: 2, body: "@1 ekşici beyler")
   Comment.create(movie_id: 1, user_id: 3, body: "@2 haklı.")
   Comment.create(movie_id: 3, user_id: 1, body: "epistemolojik olarak incelersek barok dönemden romantik döneme geçiş sürecini oldukça başarılı rerörörör")
   Comment.create(movie_id: 3, user_id: 2, body: "@1 entel beyler")
   Comment.create(movie_id: 3, user_id: 3, body: "@2 insanların görüşüne biraz saygı duyun .s .s")

   Person.create(full_name: "Nuri Bilge Ceylan", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Nuribilgeceylan.jpg/220px-Nuribilgeceylan.jpg")
   Person.create(full_name: "Daniel Day Lewis", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Daniel_Day-Lewis,_Jaguar,_Mille_Miglia_2013_cropped.jpg/220px-Daniel_Day-Lewis,_Jaguar,_Mille_Miglia_2013_cropped.jpg")
   Person.create(full_name: "Keanu Reeves", photo: "http://vignette1.wikia.nocookie.net/matrix/images/7/7b/Keanu_Reeves.jpg/revision/latest?cb=20130121015731")
   Person.create(full_name: "Andrey Tarkovsky", photo: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Andrei_Tarkovsky.jpg")
   Person.create(full_name: "Christian Bale", photo: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Christian_Bale_2009.jpg")
   Person.create(full_name: "Marlon Brando", photo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Marlon_Brando_1948.jpg")
   Person.create(full_name: "Natalie Portman", photo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Natalie_Portman_2010.jpg")
   Person.create(full_name: "Angeline Jolie", photo: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Angelina_Jolie_by_Gage_Skidmore_2.jpg")
   Person.create(full_name: "Leonardo Di Caprio", photo: "https://upload.wikimedia.org/wikipedia/commons/2/25/Leonardo_DiCaprio_2014.jpg")
   Person.create(full_name: "Marilyn Monroe", photo: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Marilyn_Monroe,_The_Prince_and_the_Showgirl,_1.jpg")
   Person.create(full_name: "Audrey Hepburn", photo: "http://images2.fanpop.com/image/photos/9400000/Audrey-audrey-hepburn-9463504-784-1011.jpg?1344144474574")
   Person.create(full_name: "Ingrid Bergman", photo: "https://upload.wikimedia.org/wikipedia/commons/b/be/Ingrid_Bergman_-_Gaslight_44.jpg")
   Person.create(full_name: "Gregory Peck", photo: "https://upload.wikimedia.org/wikipedia/commons/2/28/Gregory_Peck_1948.jpg")
   Person.create(full_name: "Hans Zimmer", photo: "https://upload.wikimedia.org/wikipedia/commons/b/be/Hans_Zimmer_2010.jpg")
   Person.create(full_name: "Hayao Miyazaki", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Hayao_Miyazaki.jpg/220px-Hayao_Miyazaki.jpg")
   Person.create(full_name: "Joe Hisaishi", photo: "https://upload.wikimedia.org/wikipedia/commons/0/00/Joe_Hisaishi_in_Krakow.JPG")
   

   UserRating.create(user_id: 1, movie_id: 1, rating: 8)
   UserRating.create(user_id: 1, movie_id: 3, rating: 7)
   UserRating.create(user_id: 1, movie_id: 5, rating: 6)
   UserRating.create(user_id: 2, movie_id: 7, rating: 7)
   UserRating.create(user_id: 2, movie_id: 2, rating: 2)
   UserRating.create(user_id: 2, movie_id: 1, rating: 8)
   UserRating.create(user_id: 3, movie_id: 4, rating: 9)
   UserRating.create(user_id: 3, movie_id: 7, rating: 7)
   UserRating.create(user_id: 3, movie_id: 6, rating: 5)
   UserRating.create(user_id: 3, movie_id: 11, rating: 3)
   UserRating.create(user_id: 3, movie_id: 13, rating: 2)
   UserRating.create(user_id: 2, movie_id: 15, rating: 4)
   UserRating.create(user_id: 2, movie_id: 1, rating: 6)
   UserRating.create(user_id: 1, movie_id: 7, rating: 6)

   MovieGenre.create(movie_id: 1, genre_id: 1)
   MovieGenre.create(movie_id: 1, genre_id: 2)
   MovieGenre.create(movie_id: 2, genre_id: 6)
   MovieGenre.create(movie_id: 2, genre_id: 3)
   MovieGenre.create(movie_id: 3, genre_id: 5)
   MovieGenre.create(movie_id: 4, genre_id: 1)
   MovieGenre.create(movie_id: 5, genre_id: 3)
   MovieGenre.create(movie_id: 5, genre_id: 8)

   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Actor')
   MoviePerson.create(movie_id: 2, person_id: 4, role: 'Actor')
   MoviePerson.create(movie_id: 3, person_id: 5, role: 'Director')
   MoviePerson.create(movie_id: 4, person_id: 6, role: 'Writer')
   MoviePerson.create(movie_id: 6, person_id: 3, role: 'Musician')
   MoviePerson.create(movie_id: 7, person_id: 1, role: 'Producer')
   MoviePerson.create(movie_id: 5, person_id: 2, role: 'Director')
   MoviePerson.create(movie_id: 8, person_id: 3, role: 'Actor')

   User.create :email => "taha@taha.com", :password => "123123123", :admin => 'f'
   User.create :email => "brk@brk.com", :password => "123123123", :admin => 'f'
   User.create :email => "admin@admin.com", :password => "123123123", :admin => 't'


   #Act, Director, Writer, Producer, Musician, 
