# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
   Genre.create(name: 'Action')
   Genre.create(name: 'Adventure')
   Genre.create(name: 'Animation')
   Genre.create(name: 'Biography')
   Genre.create(name: 'Comedy')
   Genre.create(name: 'Fantasy')
   Genre.create(name: 'Crime')
   Genre.create(name: 'Documentary')
   Genre.create(name: 'Drama')
   Genre.create(name: 'Family')
   Genre.create(name: 'Fantasy')
   Genre.create(name: 'Film-Noir')
   Genre.create(name: 'History')
   Genre.create(name: 'Horror')
   Genre.create(name: 'Music')
   Genre.create(name: 'Musical')
   Genre.create(name: 'Mystery')
   Genre.create(name: 'Romance')
   Genre.create(name: 'Sci-Fi')
   Genre.create(name: 'Short')
   Genre.create(name: 'Sport')
   Genre.create(name: 'Thriller')
   Genre.create(name: 'War')
   Genre.create(name: 'Western')

   Movie.create(title: 'The Last of The Mohicans', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'In the Name of The Father', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'My Left Foot', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Tree of Life', release_date: '2015-08-19', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Water of Life', release_date: '1995-07-08', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Breathe of Life', release_date: '2000-06-11', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Code of Life', release_date: '2011-05-30', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Error of Life', release_date: '1899-07-23', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'A Bittersweet Life', release_date: '1942-11-11', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'A Seperation', release_date: '2013-01-14', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Good, The Bad and The Ugly', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'The Matrix', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
   Movie.create(title: 'There Will Be Blood', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
	 Movie.create(title: 'The Good, The Bad and The Ugly', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
	 Movie.create(title: 'Kış Uykusu', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
	 Movie.create(title: 'Bir Zamanlar Anadolu\'da', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')
	 Movie.create(title: 'Üç Maymun', release_date: '1973-04-01', plot: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nesciunt aliquam doloremque hic neque obcaecati magni! Possimus ut assumenda eligendi quis ab sint dolores ratione dolorem perspiciatis nam quidem, voluptatem.', cover: 'yok')


   Person.create(full_name: "Nuri Bilge Ceylan", photo: "yok")
   Person.create(full_name: "Daniel Day Lewis", photo: "yok")
   Person.create(full_name: "Keanu Reeves", photo: "yok")
   Person.create(full_name: "Andrey Tarkovsky", photo: "yok")
   Person.create(full_name: "Christian Bale", photo: "yok")
   Person.create(full_name: "Marlon Brando", photo: "yok")
   Person.create(full_name: "Natalie Portman", photo: "yok")
   Person.create(full_name: "Angeline Jolie", photo: "yok")
   Person.create(full_name: "Leonardo Di Caprio", photo: "yok")
   Person.create(full_name: "Marilyn Monroe", photo: "yok")
   Person.create(full_name: "Audrey Hepburn", photo: "yok")
   Person.create(full_name: "Ingrid Bergman", photo: "yok")
   Person.create(full_name: "Gregory Peck", photo: "yok")
   Person.create(full_name: "Henry Fonda", photo: "yok")
   Person.create(full_name: "Hans Zimmer", photo: "yok")

   UserRating.create(user_id: 1, movie_id: 1, rating: 8)
   UserRating.create(user_id: 1, movie_id: 3, rating: 7)
   UserRating.create(user_id: 1, movie_id: 5, rating: 6)
   UserRating.create(user_id: 2, movie_id: 7, rating: 7)
   UserRating.create(user_id: 2, movie_id: 2, rating: 2)
   UserRating.create(user_id: 2, movie_id: 1, rating: 8)
   UserRating.create(user_id: 3, movie_id: 4, rating: 9)
   UserRating.create(user_id: 3, movie_id: 7, rating: 7)
   UserRating.create(user_id: 3, movie_id: 6, rating: 5)
   UserRating.create(user_id: 3, movie_id: 11, rating: 3)
   UserRating.create(user_id: 3, movie_id: 13, rating: 2)
   UserRating.create(user_id: 2, movie_id: 15, rating: 4)
   UserRating.create(user_id: 2, movie_id: 1, rating: 6)
   UserRating.create(user_id: 1, movie_id: 7, rating: 6)

   UserRating.create(user_id: 1, movie_id: 3)
   UserRating.create(user_id: 1, movie_id: 4)
   UserRating.create(user_id: 1, movie_id: 5)
   UserRating.create(user_id: 1, movie_id: 6)
   UserRating.create(user_id: 1, movie_id: 7)
   UserRating.create(user_id: 2, movie_id: 1)
   UserRating.create(user_id: 2, movie_id: 8)
   UserRating.create(user_id: 2, movie_id: 11)

   MovieGenre.create(movie_id: 1, genre_id: 1)
   MovieGenre.create(movie_id: 1, genre_id: 2)
   MovieGenre.create(movie_id: 2, genre_id: 6)
   MovieGenre.create(movie_id: 2, genre_id: 3)
   MovieGenre.create(movie_id: 3, genre_id: 5)
   MovieGenre.create(movie_id: 4, genre_id: 1)
   MovieGenre.create(movie_id: 5, genre_id: 3)
   MovieGenre.create(movie_id: 5, genre_id: 8)

   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Act')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Act')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Director')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Writer')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Musician')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Producer')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Director')
   MoviePerson.create(movie_id: 1, person_id: 1, role: 'Act')

   #Act, Director, Writer, Producer, Musician, 
